### ISSUE TITLE
Timeline for code release

### ISSUE THREAD

**Issue by hangzhiyiwei** [Artanic30/HOICLIP#1]
Hi, thank you for your nice paper.

I am really interested in your work and would like to know if there is a timeline for your code release. Thank you very much.

**Comment by Artanic30** [comment]
Thank you for your interest in our work.
Codes will be available in one or two weeks. Following up experiments made my codebase a mess : (
If you need it in a short time, I could update a "noisy" version :)

**Comment by hangzhiyiwei** [comment]
Thank you very much for your reply. I think a noisy version is OK for me. I wonder whether it is convenient for you to update the raw version at first.
