### ISSUE TITLE
About the pretrained model in fractional training

### ISSUE THREAD

**Issue by ChelsieLei** [Artanic30/HOICLIP#10]
Hi @Artanic30 

Thank you for your excellent work! Is it possible for you to share the pre-trained model in the 5% fractional training setting? Thank you again. 

Best,
Chelsie

**Comment by Artanic30** [comment]
Thank you for your interest in our work. However, please note that all checkpoints except the released ones have been removed. You can train the 5% data model using our scripts.

**Comment by ChelsieLei** [comment]
Thank you very much. I have re-trained, but it is always a little bit lower than what was reported, around 0.6% mAP decrease. I think it may be caused by different training environments. In this case, I may use what I have re-trained. Thank you again.

**Comment by Artanic30** [comment]
In our experiments, we notice that the performance will have a slight difference between different GPUs, such as 2080Ti and A40 GPUs. Hope this information helps you.
