### ISSUE TITLE
Zero-Shot HOI Detection Setting

### ISSUE THREAD

**Issue by hutuo1213** [Artanic30/HOICLIP#15]
Hi,
Very good work. We have recently considered using a two-stage method for Zero-Shot HOI Detection, but we have some confusion about the detailed setup. My understanding is that the text features (600) do similarity calculations with the final interaction representation to get the interaction categories.

Unseen Combination (UC): having seen the objects and actions used. The two-stage method seems to handle this case directly.  Alternatively, the "similarity computation" is still used.

Unseen Objects (UO): have not seen some of the objects. We found that existing object detectors do not have the ability to detect unseen objects. May I ask how the test is done?

Unseen Movement (UV)：there are some unseen actions. Does this part still use "similarity computation"?

**Comment by Artanic30** [comment]
Thanks for interested in our work. Under zero-shot setting, the unseen class samples are not in the training set, however, the unseen class names are known during training which means the classifiers for object detection and hoi classification are inited with unseen class names and seen class names. So the "similarity computation" is still used. I hope this could sovle your question. If you have any futher quesiton, feel free to disscuss here.

**Comment by hutuo1213** [comment]
Thanks!
