### ISSUE TITLE
Is the training_free_enhancement part required during zero-shot training?

### ISSUE THREAD

**Issue by sandipan211** [Artanic30/HOICLIP#16]
Hi @Artanic30 ,

Kudos for this impressive work. I was trying to train your network using the command:
```
sh ./scripts/train_hico_rf_uc.sh
```
However, in all these scripts you have used the flag: "--training_free_enhancement_path". This turns your hyperparameter tuning step on at [this](https://github.com/Artanic30/HOICLIP/blob/8d871c4298a3e279d93cc8574bca82b732764c6a/engine.py#L234) line. However, the results from this tuning step do not have any effect on training. Instead, the resulting mAPs from the evaluation step done at the [end](https://github.com/Artanic30/HOICLIP/blob/8d871c4298a3e279d93cc8574bca82b732764c6a/engine.py#L291) (what you call as "Baseline performance") is returned and decides whether to not to update your training checkpoint.

So my question is: Is having the flag "--training_free_enhancement_path" really necessary **while training**? Or can it be omitted, since it is very time-consuming?

**Comment by Artanic30** [comment]
Thanks for interested in our work. The --training_free_enhancement_path is only used in evaluation, so it can be omitted in  training.
