### ISSUE TITLE
Testing V-COCO and KO setting in HICO-DET

### ISSUE THREAD

**Issue by sandipan211** [Artanic30/HOICLIP#17]
Hi @Artanic30 ,

Can you kindly provide the command for testing vcoco? Moreover, since there are two evaluation settings (default and known object (KO)) in the supervised evaluation of HICO-DET, can you please provide the command to run for evaluating the KO setting? As per your scripts, I think it is only the default setting evaluation - can you please guide me?

**Comment by Artanic30** [comment]
Sorry for the late reply. The results for VCOCO will be available in the log if you launch the training scripts in *scripts/train_vcoco.sh*. For KO setting, I remember that I follow the instruction in [GEN-VLKT](https://github.com/YueLiao/gen-vlkt?tab=readme-ov-file#hico-det-2), which leads to code in [DDPM](https://github.com/YueLiao/PPDM#test).

**Comment by sandipan211** [comment]
Thanks for the reply - I will look into it. 

One more thing - I could not find checkpoints in your work for the UC setting. There are 5 different zero-shot UC splits, but none of those checkpoints are there in your repository - or even the scripts for training/testing UC setting. Can you please provide the UC checkpoints?

**Comment by Artanic30** [comment]
The checkpoint for UC setting is in https://github.com/Artanic30/HOICLIP#zero-shot-hoi-detection-results, could you take a look at these sections. If anything is not working, please let me know.

**Comment by sandipan211** [comment]
Thanks, but these are RF-UC and NF-UC checkpoints. I need to run for [uc0](https://github.com/Artanic30/HOICLIP/blob/8d871c4298a3e279d93cc8574bca82b732764c6a/datasets/hico_text_label.py#L536), [uc1](https://github.com/Artanic30/HOICLIP/blob/8d871c4298a3e279d93cc8574bca82b732764c6a/datasets/hico_text_label.py#L547),...uc4, on the basis of which we get results in UC setting finally. Could you please provide checkpoints corresponding to these?

**Comment by Artanic30** [comment]
Sorry for the misunderstanding. Igot your point, checkpoints will be updated very soon.

**Comment by Artanic30** [comment]
Hi, we also provide the checkpoints for uc0, uc1, uc2, uc3 settings in [Google Drive](https://drive.google.com/drive/folders/1NddLSPHbNZXlxmIQbcobh2O5KKWAITRo?usp=drive_link)
Could you take a look at these ckpts.

**Comment by sandipan211** [comment]
Kindly provide access to the files in the drive link 😅

**Comment by Artanic30** [comment]
I change the accessibility and the link should be available to everyone now.

**Comment by sandipan211** [comment]
Thanks a ton! Just one more thing - for uc4 I think you haven't uploaded in that link. Can you kindly provide that as well?

**Comment by Artanic30** [comment]
I'm sorry to say that I think the uc4 model is deleted by mistake...
It's has been a long time since these experiments are conducted and I failed to find it on my server.

**Comment by sandipan211** [comment]
Oh 😞 
Okay still - thanks for the response
