### ISSUE TITLE
关于HICO-DET数据集

### ISSUE THREAD

**Issue by chencn2020** [Artanic30/HOICLIP#19]
你好，HICO-DET数据集的下载链接失效了，能重新分享一份吗

**Comment by Artanic30** [comment]
Hi, is this [commit](https://github.com/Artanic30/HOICLIP/commit/ee4db062097410abdd20fa96d40d26aaca1f19da) resolve your concerns?

**Comment by chencn2020** [comment]
Yes, thank you!
