### ISSUE TITLE
error of the CLIP image_encoder

### ISSUE THREAD

**Issue by hangzhiyiwei** [Artanic30/HOICLIP#2]
Hi, thank you for your nice work.

I came across an error here [https://github.com/Artanic30/HOICLIP/blob/main/models/models_hoiclip/gen.py#L121](url). 

'''
Exception has occurred: ValueError
too many values to unpack (expected 2)
'''

I referred to the CLIP description, and the output of "encode_image" method is only one. [https://github.com/openai/CLIP/blob/main/clip/model.py#L340](url). Maybe there is something missing in your code?

Any reply will be appreciated. Thank you very much.

**Comment by Artanic30** [comment]
Sorry, I forgot to upload modifed CLIP codes.
The issue is fixed in https://github.com/Artanic30/HOICLIP/commit/eca6c460e3758c8ee56e73f716cad78fb565c2d9
Thanks for pointing out the bug.
