### ISSUE TITLE
About hico-det Known object Setting

### ISSUE THREAD

**Issue by TCK2001** [Artanic30/HOICLIP#21]
How to perform "known object Setting" on  HICO-DET dataset ?

**Comment by Artanic30** [comment]
Hi, you may follow the instruction in Section "HICO-DET official evalution" from [PPDM](https://github.com/YueLiao/PPDM?tab=readme-ov-file#test).

**Comment by TCK2001** [comment]
Thank you for your response.
Are you referring to [PPDM](https://github.com/YueLiao/PPDM?tab=readme-ov-file#test) "Test 2: For HICO-DET official evaluation"? I am not sure where to obtain the JSON files.
Is there a way to directly call and apply the code, similar to how hico_eval_triplet.py works, without using PPDM?

I'll be waiting for your response. Thank you.

**Comment by sandipan211** [comment]
Hi @TCK2001,

Can you tell me how you solved this problem? I do have the json file, but when I try following the PPDM steps I get the following error:
```
Traceback (most recent call last):
  File "trans_for_eval_hico.py", line 246, in <module>
    Generate_HICO_detection(json_file, folder+'ppdm_results/')
  File "trans_for_eval_hico.py", line 158, in Generate_HICO_detection
    HICO = Format_Pred(output_file)
  File "trans_for_eval_hico.py", line 104, in Format_Pred
    annot_bbox = annot['predictions']
TypeError: string indices must be integers
```

I also tried converting into official prediction format using [this](https://github.com/YueLiao/gen-vlkt/blob/master/tools/covert_annot_for_official_eval.py) file, I am getting another error:
```
Traceback (most recent call last):
  File "covert_annot_for_official_eval.py", line 148, in <module>
    Generate_HICO_detection(json_file, folder+'ppdm_results/')
  File "covert_annot_for_official_eval.py", line 63, in Generate_HICO_detection
    save_HICO(HICO, HICO_dir, 1, 161, 170)  # 1 person
  File "covert_annot_for_official_eval.py", line 50, in save_HICO
    sio.savemat(savefile, {'all_boxes': all_boxes})
  File "/workspace/udit/anaconda3/envs/zshoi_24/lib/python3.8/site-packages/scipy/io/matlab/_mio.py", line 298, in savemat
    MW.put_variables(mdict)
  File "/workspace/udit/anaconda3/envs/zshoi_24/lib/python3.8/site-packages/scipy/io/matlab/_mio5.py", line 892, in put_variables
    self._matrix_writer.write_top(var, name.encode('latin1'), is_global)
  File "/workspace/udit/anaconda3/envs/zshoi_24/lib/python3.8/site-packages/scipy/io/matlab/_mio5.py", line 633, in write_top
    self.write(arr)
  File "/workspace/udit/anaconda3/envs/zshoi_24/lib/python3.8/site-packages/scipy/io/matlab/_mio5.py", line 651, in write
    narr = to_writeable(arr)
  File "/workspace/udit/anaconda3/envs/zshoi_24/lib/python3.8/site-packages/scipy/io/matlab/_mio5.py", line 493, in to_writeable
    narr = np.asanyarray(source)
ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 2 dimensions. The detected shape was (11255, 5) + inhomogeneous part.
```

Can you please help me out @TCK2001 , @Artanic30 ?

**Comment by TCK2001** [comment]
hello @sandipan211 
You need to convert the file generated by models like gen-vlkt or HOICLIP, as this error indicates that your format is not compatible with the PPDM format.

* When I used the `convert_to_official` file provided by gen-vlkt, I was able to run it without any issues.     

Looking at your error message, it seems that there is an issue with the `output format`.

**Comment by sandipan211** [comment]
> hello @sandipan211 You need to convert the file generated by models like gen-vlkt or HOICLIP, as this error indicates that your format is not compatible with the PPDM format.
> 
> * When I used the `convert_to_official` file provided by gen-vlkt, I was able to run it without any issues.
> 
> Looking at your error message, it seems that there is an issue with the `output format`.

Thanks for commenting. Can you tell me how you generated your json file that contains the detection results?

**Comment by TCK2001** [comment]
The json file is too big to show in here....

(Recommend) Just run the code from the authors of GEN-VLKT or HOICLIP to check the JSON file format !!

**Comment by sandipan211** [comment]
> The json file is too big to show in here....
> 
> (Recommend) Just run the code from the authors of GEN-VLKT or HOICLIP to check the JSON file format !!

Well I have got similar format results in my JSON file like you sent, but it's still not working. Anyway, thanks. I'll keep figuring it out.

**Comment by sandipan211** [comment]
> Hi @TCK2001,
> 
> Can you tell me how you solved this problem? I do have the json file, but when I try following the PPDM steps I get the following error:
> 
> ```
> Traceback (most recent call last):
>   File "trans_for_eval_hico.py", line 246, in <module>
>     Generate_HICO_detection(json_file, folder+'ppdm_results/')
>   File "trans_for_eval_hico.py", line 158, in Generate_HICO_detection
>     HICO = Format_Pred(output_file)
>   File "trans_for_eval_hico.py", line 104, in Format_Pred
>     annot_bbox = annot['predictions']
> TypeError: string indices must be integers
> ```
> 
> I also tried converting into official prediction format using [this](https://github.com/YueLiao/gen-vlkt/blob/master/tools/covert_annot_for_official_eval.py) file, I am getting another error:
> 
> ```
> Traceback (most recent call last):
>   File "covert_annot_for_official_eval.py", line 148, in <module>
>     Generate_HICO_detection(json_file, folder+'ppdm_results/')
>   File "covert_annot_for_official_eval.py", line 63, in Generate_HICO_detection
>     save_HICO(HICO, HICO_dir, 1, 161, 170)  # 1 person
>   File "covert_annot_for_official_eval.py", line 50, in save_HICO
>     sio.savemat(savefile, {'all_boxes': all_boxes})
>   File "/workspace/udit/anaconda3/envs/zshoi_24/lib/python3.8/site-packages/scipy/io/matlab/_mio.py", line 298, in savemat
>     MW.put_variables(mdict)
>   File "/workspace/udit/anaconda3/envs/zshoi_24/lib/python3.8/site-packages/scipy/io/matlab/_mio5.py", line 892, in put_variables
>     self._matrix_writer.write_top(var, name.encode('latin1'), is_global)
>   File "/workspace/udit/anaconda3/envs/zshoi_24/lib/python3.8/site-packages/scipy/io/matlab/_mio5.py", line 633, in write_top
>     self.write(arr)
>   File "/workspace/udit/anaconda3/envs/zshoi_24/lib/python3.8/site-packages/scipy/io/matlab/_mio5.py", line 651, in write
>     narr = to_writeable(arr)
>   File "/workspace/udit/anaconda3/envs/zshoi_24/lib/python3.8/site-packages/scipy/io/matlab/_mio5.py", line 493, in to_writeable
>     narr = np.asanyarray(source)
> ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 2 dimensions. The detected shape was (11255, 5) + inhomogeneous part.
> ```
> 
> Can you please help me out @TCK2001 , @Artanic30 ?

Apparently, the error was arising due to numpy incompatibility 🤦  - I had version 1.24 installed, but to run this conversion file, I had to downgrade to Numpy 1.21.1 - after that, it worked as desired. Thanks @TCK2001 .

**Comment by TCK2001** [comment]
Omg ....

I'm glad it was resolved.
Have a great day~
