### ISSUE TITLE
code for visualization

### ISSUE THREAD

**Issue by hangzhiyiwei** [Artanic30/HOICLIP#3]
Hi, thank you for your nice work.

I wonder whether there is a code for the visualization of the attention map in Figure 5 in your paper.
![image](https://user-images.githubusercontent.com/48050514/232408126-0d241f2e-184b-4e45-b92c-095d890ad4e9.png)

Thank you very much.

**Comment by Artanic30** [comment]
Hi, the code for visualization is updated in https://github.com/Artanic30/HOICLIP/commit/544c01af7b8ff55b70d8db81eaae7db98678e645

Script for visualization is in scripts/visualization_hico.sh
You may need to adjust the file paths with TODO comment in _visualization_hoiclip/gen_vlkt.py_ and currently the code visualize fail cases in some zero-shot setting. For detail information, you may refer to the comments.

**Comment by hangzhiyiwei** [comment]
Thank you very much for your reply and sharing!

**Comment by hangzhiyiwei** [comment]
Hi, sorry to disturb you again. I have another problem. Your code for visualization is the visualization of the GEN-VLKT model. It may not be the code in your paper?

**Comment by Artanic30** [comment]
Sorry for the mistake. 

If you want to visualize HOICLIP, you could copy the code in visualization_hoiclip/et_gen.py to visualization_hoiclip/gen.py
These two file are used to generate GEN-VLKT and HOICLIP visualization in paper. We just switch them mannually :)

**Comment by hangzhiyiwei** [comment]
Oh, understand. It works. Thank you very much!

**Comment by hn-uu** [comment]
Hi, I’d like to ask a question regarding the visualization of the HOICLIP model. I followed the instructions by copying the code from visualization_hoiclip/et_gen.py into visualization_hoiclip/gen.py, and I also adjusted the file paths as per the TODO comments in visualization_hoiclip/gen_vlkt.py.

The code runs without errors, but there are no images being generated in the output directory. Could you please advise what might be going wrong or what additional steps I should take?
This is my command output：
<img width="732" alt="微信图片_20240921140236" src="https://github.com/user-attachments/assets/eab56977-b60a-4686-9b33-decbd81d4883">
