### ISSUE TITLE
Question about the training-free enhancement

### ISSUE THREAD

**Issue by hangzhiyiwei** [Artanic30/HOICLIP#4]
Hi, thank you for your excellent work.

I found that in your paper, you provide the result **without** the training-free enhancement. However, without the training-free enhancement of the prior knowledge of CLIP, how can you get the classification information for unseen HOI classes during inference?

Thank you very much!

**Comment by Artanic30** [comment]
Hi, please kindly refer to https://github.com/Artanic30/HOICLIP/commit/2eb12726be0baa05a57eddd50920717d3130f2a3

The training free enhancement is evaluated after all the samples are predicted by HOICLIP. You may find the codes with comments in engine.py with an additionale argument parameter in main.py

**Comment by hangzhiyiwei** [comment]
Thank you for your reply.

**Comment by mrwu-mac** [comment]
A good work. But I have the same problem,  it should not be able to do zero-shot inference without CLIP text label.
