### ISSUE TITLE
Question about the verb class representation

### ISSUE THREAD

**Issue by hangzhiyiwei** [Artanic30/HOICLIP#5]
Hi, thank you for your nice work. 

I have a question about the verb class representation.
![image](https://user-images.githubusercontent.com/48050514/234165358-e7e5b8bc-7d84-4b0e-93c9-f90ae9f75562.png)

In the above figure, are the bounding boxes of the human and object obtained from ground truth? 
If so, does it mean you use the unseen HOI class image and their ground truth bounding boxes for training?

Thank you very much.

**Comment by hangzhiyiwei** [comment]
Hi, I only want to check for sure. Actually, the EoID paper uses the unseen HOI class image's GT Bboxes for training ([End-to-End Zero-Shot HOI Detection via Vision and Language Knowledge Distillation](https://arxiv.org/abs/2204.03541), AAAI2023).

**Comment by Artanic30** [comment]
Hi, it has been a busy week for me.
We extract all verb class representation under training data in default (fully supervised) HOI setting . So, it's true we use the unseen HOI class image's GT Bounding boxes for training.

**Comment by hangzhiyiwei** [comment]
Oh, I understand it. Thanks for your kind reply.
