### ISSUE TITLE
Issue in performing evaluation using given model

### ISSUE THREAD

**Issue by agneytalwar** [Artanic30/HOICLIP#8]
Hi, Thank you for your nice work.
I am facing an issue while replicating your evaluation results in Zero-shot HOI Detection using the pretrained model provided by you.
I ran the following command after downloading the model.
`python -m torch.distributed.launch \
        --use_env \
        main.py \
        --pretrained ./checkpoint_rf_uc.pth \
        --dataset_file hico \
        --hoi_path ../data/hico_20160224_det \
        --num_obj_classes 80 \
        --num_verb_classes 117 \
        --backbone resnet50 \
        --num_queries 64 \
        --dec_layers 3 \
        --eval \
        --with_clip_label \
        --with_obj_clip_label \
        --use_nms_filter \
        --zero_shot_type rare_first \
        --del_unseen`
This is the error I face:
![image](https://github.com/Artanic30/HOICLIP/assets/83603213/769b45f4-5151-4975-8618-0ff6d595ae05)

I would be grateful if you could resolve this.

**Comment by jiaochao0823** [comment]
how you solve this error?
