### ISSUE TITLE
generate_vcoco_official.py

### ISSUE THREAD

**Issue by aqingcv** [Artanic30/HOICLIP#9]
Hello, thank you for your nice work.
Could you provide the generate_vcoco_official.py? Thx!

**Comment by Artanic30** [comment]
Hi, thanks for interested in our work. Acutally, we directly report the results from engine.py:286, which is computed by datasets/datasets_gen/vcoco_eval.py. So we didn't implement generate_vcoco_official.py. We will modified the readme.md and sorry for the inconvenience.
